# Generated by Django 5.2.1 on 2025-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoRaices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.CharField(max_length=200)),
                ('metodo_utilizado', models.CharField(choices=[('BISECCION', 'Bisección'), ('NEWTON_RAPHSON', 'Newton-Raphson'), ('NEWTON_RAPHSON_MODIFICADO', 'Newton-Raphson Modificado')], max_length=30)),
                ('respuesta', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cálculo de Calculadora',
                'verbose_name_plural': 'Cálculos de Calculadora',
                'ordering': ['-fecha_y_hora'],
            },
        ),
    ]
