# Generated by Django 5.2.1 on 2025-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_calculoraices'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoraices',
            name='iteraciones',
            field=models.IntegerField(default=0),
        ),
    ]
