# Generated by Django 5.2.1 on 2025-06-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_calculoraices_iteraciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacks',
            name='project',
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
        migrations.DeleteModel(
            name='Tacks',
        ),
    ]
